site_name: $SITE_NAME$
site_description: Documentation for $SITE_NAME$
docs_dir: docs
site_dir: site

theme:
  name: material
  palette:
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.indexes
    - navigation.tabs
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.superfences
  - tables

nav:
  - Index: index.md

extra_css:
  - stylesheets/extra.css
